name: get_apps
description: A plugin that allows you to get a list of messengers, emails or run any other application
version: 0.0.1
homepage: https://github.com/mm-terekhin/get_apps
repository: https://github.com/mm-terekhin/get_apps

environment:
  sdk: ^3.5.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.mm_terekhin.get_apps
        pluginClass: GetAppsPlugin
      ios:
        pluginClass: GetAppsPlugin

  assets:
    - assets/
